CREATE TABLE PROPERTIES
(
  ID_          INTEGER NOT NULL,
  KEY_         NVARCHAR2(255) NOT NULL,
  VALUE_       NVARCHAR2(255) NOT NULL,
  APPLICATION_ NVARCHAR2(255) NOT NULL,
  PROFILE_     NVARCHAR2(255) NOT NULL,
  LABEL_       NVARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID_)
)